name: nufit
description: "A tailor made app for losing weights and confidence."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.10.4 
  image_picker: ^1.0.7
  image: ^4.0.17
  firebase_core: ^2.25.3
  firebase_auth: ^4.16.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  fl_chart: ^0.66.1
  percent_indicator: ^4.2.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.15.3
  random_string: ^2.3.1
  firebase_storage: ^11.6.4
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true 
  assets:
   - assets/icons/
   - assets/models/
   - assets/images/
